FORMAT: 1A
HOST: {{ $apiUrl }}/

{{-- Inject the model factory so entities be declared with factories --}}
@inject('factory', 'App\Services\ModelFactory')


# Spira API

Spira is a full stack boilerplate with a REST api build on [Lumen](http://lumen.laravel.com)

## Current status
* Hostname:
    * Local: local.api.spira.io
    * Production: (Not implemented)
* Encryption: none
* Protocol: http
* Port: 8080

## Restrictions
Each endpoint may have restrictions. These are defined as a cascading whitelist.
e.g. the following definiton means everyone is denied _except_ admins
```
* Denied - [all]
* Allowed - [admin]
```

# Group Spira API Root
You're looking at it! This route provides this documentation, it is configured at `spira/api/resources/views/documentation/`
You can use both `$factory` and `$faker`. Note that `$factory` is a custom model factory service which allows more
flexibility than the base laravel `factory()` methods.

@include('documentation.sections.testEntity')
@include('documentation.sections.auth')
@include('documentation.sections.user')
@include('documentation.sections.timezones')
@include('documentation.sections.countries')
