FORMAT: 1A
HOST: {{ $apiUrl }}/

{{-- Inject the model factory so entities be declared with factories --}}
@inject('factory', 'App\Services\ModelFactory')


# Spira API

Spira is a full stack boilerplate with a REST api build on [Lumen](http://lumen.laravel.com) 

## Current status
* Hostname:
    * Local: local.api.spira.io
    * Production: (Not implemented)
* Encryption: none
* Protocol: http
* Port: 8080

## Restrictions
Each endpoint may have restrictions. These are defined as a cascading whitelist.
e.g. the following definiton means everyone is denied _except_ admins
```
* Denied - [all]
* Allowed - [admin]
```

# Spira API Root [/]

This route provides this documentation!

@include('documentation.sections.testEntity')

@include('documentation.sections.auth')

@include('documentation.sections.user')