# Group Articles
Articles are the generic posts/blogs of the system, they are used to display static CMS content.

## Article Collection [/articles]
The collection of all article posts.

### Retrieve all articles [GET]
Note that this route returns paginated results as defined in the `Content-Range` headers

#### Restrictions
* Published - Allowed - [all]
* Unpublished - Allowed - [admin, self]
+ Request
    + Headers

            Range: entities=0-

+ Response 200 (application/json)

    + Headers

            Accept-Ranges: entities
            Content-Range: entities 0-9/200

    + Body

            {!!
                $factory->get(\App\Models\Article::class)
                    ->setTransformer(App\Http\Transformers\ArticleTransformer::class)
                    ->count(10)
                    ->json()
            !!}


## Article Entity [/articles/{articleId}]

+ Parameters
    + articleId (required, uuid, `{!! $faker->uuid !!}`) ... Unique `id` or `uri` of the article to perform action with.


### Retrieve an article [GET]

#### Restrictions
* Published - Allowed - [all]
* Unpublished - Allowed - [admin, self]
+ Response 200 (application/json)

    + Body

            {!! $factory->json(\App\Models\Article::class) !!}

### Create/update article entity [PUT]

#### Restrictions
* Allowed - [admin, self]

+ Request
    + Body

            {!! $factory->json(\App\Models\Article::class) !!}

+ Response 201

### Update the article [PATCH]

#### Restrictions
* Allowed - [admin, self]

+ Request
    + Body

            {!!
                $factory->get(\App\Models\Article::class)
                    ->hide(['_self'])
                    ->showOnly(['content'])
                    ->json()
            !!}


+ Response 204


### Delete the article [DELETE]
#### Restrictions
* Allowed - [admin, self]

+ Response 204

## Article Permalinks [/articles/{articleId}/permalinks]
+ Parameters
    + articleId (required, uuid, `{!! $faker->uuid !!}`) ... Unique `id` or `uri` of the article to perform action with.

### Retrieve all article's permalinks [GET]
#### Restrictions
* Allowed - [admin, self]

+ Response 200 (application/json)
    + Body

            {!!
                $factory->get(\App\Models\ArticlePermalink::class)
                    ->count(3)
                    ->json()
            !!}

## Article Meta [/articles/{articleId}/meta]
+ Parameters
    + articleId (required, uuid, `{!! $faker->uuid !!}`) ... Unique `id` or `uri` of the article to perform action with.

### Retrieve all article's meta data [GET]
#### Restrictions
* Allowed - [all]

+ Response 200 (application/json)
    + Body

            {!!
                $factory->get(\App\Models\ArticleMeta::class)
                    ->count(3)
                    ->json()
            !!}

### Bulk create/update article meta data [PUT]

#### Restrictions
* Allowed - [admin, self]

+ Request
    + Body

            {!!
                $factory->get(\App\Models\ArticleMeta::class)
                    ->count(3)
                    ->json()
            !!}

+ Response 201

## Article Meta Deletion [/articles/{articleId}/meta/{metaName}]
+ Parameters
    + articleId (required, uuid, `{!! $faker->uuid !!}`) ... Unique `id` or `uri` of the article to perform action with.
    + metaName (required, string, `twitter`) ... Meta data name

### DELETE article's meta data single record [DELETE]
#### Restrictions
* Allowed - [admin, self]

+ Response 204

## Article Tags [/articles/{articleId}/tags]
+ Parameters
    + articleId (required, uuid, `{!! $faker->uuid !!}`) ... Unique `id` or `uri` of the article to perform action with.

### Retrieve all article's tags data [GET]
#### Restrictions
* Allowed - [all]

+ Response 200 (application/json)
    + Body

            {!!
                $factory->get(\App\Models\Tag::class)
                    ->setTransformer(App\Http\Transformers\ArticleTagTransformer::class)
                    ->count(3)
                    ->json()
            !!}

### Add tags to article [PUT]

+ Request
    + Body

            {!!
                $factory->get(\App\Models\Tag::class)
                    ->hide(['_self'])
                    ->json()
            !!}

+ Response 201 (application/json)
    + Body

            {!!
                $factory->get(\App\Models\Tag::class)
                    ->showOnly(['_self'])
                    ->json()
            !!}


## Article Comments [/articles/{articleId}/comments]

+ Parameters
    + articleId (required, uuid, `{!! $faker->uuid !!}`) ... Unique `id` of the article to get comments for.

### Retrieve all comments for article [GET]
#### Restrictions
* Allowed - [all]

+ Response 200 (application/json)
    + Body

            {!!
                $factory->get(\App\Models\ArticleComment::class)
                    ->append('_author',
                        $factory->get(\App\Models\User::class)
                            ->showOnly(['user_id', 'username', 'first_name', 'last_name', 'avatar_img_url'])
                            ->hide(['_self'])
                            ->transformed()
                    )
                    ->count(3)
                    ->json()
            !!}

### Post a comment for article [POST]
#### Restrictions
* Allowed - [all]

+ Request
    + Headers

            Authorization: Bearer {!! $factory->make(\App\Models\AuthToken::class)->token !!}

    + Body

            {!!
                $factory->get(\App\Models\ArticleComment::class)
                    ->showOnly(['body'])
                    ->json();
            !!}


+ Response 200 (application/json)
    + Body

            {!!
                $factory->get(\App\Models\ArticleComment::class)
                    ->append('_author',
                        $factory->get(\App\Models\User::class)
                            ->showOnly(['user_id', 'username', 'first_name', 'last_name', 'avatar_img_url'])
                            ->hide(['_self'])
                            ->transformed()
                    )
                    ->json()
            !!}


## Article Images [/articles/{articleId}/article-images]
+ Parameters
    + articleId (required, uuid, `{!! $faker->uuid !!}`) ... Unique `id` or `uri` of the article to perform action with.

### Retrieve all article's images [GET]
#### Restrictions
* Allowed - [all]

+ Response 200 (application/json)
    + Body

            {!!
                $factory->get(\App\Models\ArticleImage::class)
                    ->append('articleId',$faker->uuid)
                    ->append('_image',
                        $factory->get(\App\Models\Image::class)
                            ->append('imageId',$faker->uuid)
                            ->transformed()
                    )
                    ->count(3)
                    ->json()
            !!}

### Add images to article [PUT]
#### Restrictions
* Allowed - [admin]

+ Request
    + Body

            {!!
                $factory->get(\App\Models\ArticleImage::class)
                    ->append('articleId',$faker->uuid)
                    ->append('imageId',$faker->uuid)
                    ->count(3)
                    ->hide(['_self'])
                    ->json()
            !!}

+ Response 201 (application/json)
    + Body

            {!!
                $factory->get(\App\Models\ArticleImage::class)
                    ->showOnly(['_self'])
                    ->json()
            !!}

### Delete images [DELETE]
#### Restrictions
* Allowed - [admin]

+ Request
    + Body

            {!!
                $factory->get(\App\Models\ArticleImage::class)
                    ->showOnly(['article_image_id'])
                    ->count(3)
                    ->json()
            !!}

+ Response 204

