# Group Child Test
The test path is for all child entity tests for the spira core, included are some specific tests for checking functionality of the base system such as exceptions.

## Test Children Entities [/test/entities/{entityId}/children]
Test entities are provided as an example to cover most of the bases of what is required for a REST api. It includes
 both unit and integration tests to verify functionality.
 
+ Parameters
    + entityId (required, uuid, `c061c86e-a4c9-351b-a6d5-8739bf293303`) ... Unique `id` of the test entity to perform action with.

### Retrieve all test entities [GET]

+ Response 200 (application/json)

    + Body

            {!! $factory->get(\App\Models\SecondTestEntity::class)->count(2)->json() !!}
            


## Test Entity [/test/entities/{entityId}/child/{childId}]

+ Parameters
    + entityId (required, uuid, `c061c86e-a4c9-351b-a6d5-8739bf293303`) ... Unique `id` of the test entity to perform action with.
    + childId (required, uuid, `c061c86e-a4c9-351b-a6d5-8739bf293302`) ... Unique `id` of the child test entity to perform action with.


### Retrieve a test entity [GET]
+ Response 200 (application/json)

    + Body

            {!! $factory->json(\App\Models\SecondTestEntity::class) !!}


