# Group Timezones

## All timezones [/timezones]
Users can set their timezone which is used for monitoring when (for example), a post should be visible to a user or
when a user should have a daily email dispatched.
have their emails dispatched.

### Get all timezones [GET]
#### Restrictions
* Allowed - [all]

+ Response 200 (application/json)

    + Body

            {!! 
                $factory->get()
                    ->setCollection(App::make('Spira\Core\Model\Datasets\Timezones')->all())
                    ->count(5)
                    ->json() 
            !!}

