# Group Users
Every visitor to the site is a user variant, they have the same entity priority whether they are an admin or a public
 (logged in) user. Their roles, permissions and access levels are handled independently, but linked to their account.

## User collection [/users]

### Get all users [GET]
#### Restrictions
* Denied - [all]
* Allowed - [admin]

+ Request
    + Headers

            Authorization: Bearer {!! $factory->make(\App\Models\AuthToken::class)->token !!}

+ Response 200 (application/json)

    + Body

            {!! $factory->get(\App\Models\User::class)->count(5)->json() !!}

## User entity [/users/{userId}]
+ Parameters
    + userId (required, uuid, `{!! $faker->uuid !!}`) ... Unique `id` of the user entity to perform action with.

### Get user entity [GET]
#### Restrictions
* Denied - [all]
* Allowed - [admin, self]

+ Request
    + Headers

            Authorization: Bearer {!! $factory->make(\App\Models\AuthToken::class)->token !!}

+ Response 200 (application/json)

    + Body

            {!! $factory->json(\App\Models\User::class) !!}


### Create/Register user entity [PUT]
* Note that for this entity replacement of entity is *not* permitted
#### Restrictions
* Allowed - [all]

+ Request
    + Headers
    + Body

            {!!
                $factory->get(\App\Models\User::class)
                    ->makeVisible(['password'])
                    ->showOnly(['userId', 'email', 'firstName', 'lastName'])
                    ->json();
            !!}

+ Response 204

### Update user entity [PATCH]
#### Restrictions
* Allowed - [admin, self]

+ Request
    + Headers

            Authorization: Bearer {!! $factory->make(\App\Models\AuthToken::class)->token !!}

    + Body

            {!!
                $factory->get(\App\Models\User::class)
                    ->showOnly(['user_id', 'first_name'])
                    ->json()
            !!}

+ Response 204

### Delete user entity [DELETE]
#### Restrictions
* Allowed - [admin]

+ Request
    + Headers

            Authorization: Bearer {!! $factory->make(\App\Models\AuthToken::class)->token !!}

+ Response 204
