## Article Tags [/articles/{articleId}/tags]
+ Parameters
    + articleId (required, uuid, `{!! $faker->uuid !!}`) ... Unique `id` or `uri` of the article to perform action with.

### Retrieve all article's tags data [GET]
#### Restrictions
* Allowed - [all]

+ Response 200 (application/json)
    + Body

            {!!
                $factory->get(\App\Models\Tag::class)
                    ->count(3)
                    ->json()
            !!}

### Add tags to article [PUT]

+ Request
    + Body

            {!!
                $factory->get(\App\Models\Tag::class)
                    ->hide(['_self'])
                    ->json()
            !!}

+ Response 201 (application/json)
    + Body

            {!!
                $factory->get(\App\Models\Tag::class)
                    ->showOnly(['_self'])
                    ->json()
            !!}

